[project]
name = "langgraph-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langchain-anthropic>=0.3.0",
    "langgraph>=0.2.59",
    "langsmith>=0.2.3",
    "ruff>=0.8.3",
]
